### ISSUE TITLE
Questions about returning log values

### ISSUE THREAD

**Issue by jeancochrane** [dedupeio/datetime-distance#1]
Two questions about the comparator's return values:

1. For every resolution, we return the log of the delta between the two inputs ([example here](https://github.com/dedupeio/datetime-distance/blob/master/datetime_distance/__init__.py#L91)). This makes sense to me at the seconds resolution, where the distance is often very large, but is it also the right call for days, months, and years?

2. We're taking the log of the difference (`log(x - y)`) as opposed to the difference of the logs (`log(x) - log(y)`). I'm unclear on the theory behind this choice so I don't know if it matters, but it's technically different than the example in [the price comparator](https://github.com/dedupeio/dedupe/blob/dced1811ba7a2a446ee69669761e05f448d04f59/dedupe/variables/price.py#L18), which I based this calculation on. Is it fine like this?

Curious to hear your thoughts @fgregg. I won't be working on this until Tuesday, so no rush.

**Comment by fgregg** [comment]
Let me take the second question first

The difficult with the `log(x-y)` is that `log(0)` is undefined.  This is why I go through the gyrations i do with the price comparator. Unfortunately, we can't really do the same thing since prices is a ratio variable but time is only an interval variable (see http://www.graphpad.com/support/faqid/1089/ for what this means, but basically we can say that one price is 50% higher than other price, but it doesn't make any sense to say that may 15, 1957 is 50% later than jan 1, 1852.

So... since, we are going to have zeros.  we can't really use logs.  Now let's get to your first question. The reasons that I *wanted* to use logs is the intuition that the difference between 3 days and 2 days is, in some sense, more important than the difference between 1000 days and 999 days even though in both cases the differences between the respective values is just one day. 

There are other ways to do this, for example power transforms.. https://en.wikipedia.org/wiki/Power_transform

Why don't you look at this for an hour or so, and then let's talk about it.

**Comment by jeancochrane** [comment]
We would up using the square root function. See [this comment](https://github.com/dedupeio/datetime-distance/blob/master/datetime_distance/__init__.py#L87-L90) for a note on why.
